target 'shopProchase' do
pod 'SDWebImage', '~> 4.4.7'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJExtension', '~> 3.0.11'
pod 'TZImagePickerController'
pod 'Masonry'
pod 'SGQRCode'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'JPush'
pod 'UICollectionViewLeftAlignedLayout'
pod 'HMSegmentedControl'
pod 'BRPickerView'
pod 'GKPhotoBrowser'
pod 'SGQRCode'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCCommonLog'
pod 'ReactiveObjC'
pod 'GKPageScrollView'
pod 'JXCategoryView'
pod 'GKNavigationBarViewController'
end
